velodyne_driver_node:
    ros__parameters:
        device_ip: 195.0.0.70
        gps_time: true
        time_offset: 0.0
        enabled: true
        read_once: false
        read_fast: false
        repeat_delay: 0.0
        frame_id: velodyne
        model: 32C
        rpm: 600.0
        pcap: ""
        port: 2368
        timestamp_first_packet: false
